# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Redirect stderr to a given file.
#'
#' This function redirects the standard error (stderr) to a new file
#' descriptor, pointing to the file at `filepath`.
#'
#' @param filepath The path to the desired file. Must not be null.
#'
#' @param append Controls whether the text should be appended if the
#'   file already exists. By default (`false`), truncates the file.
#'
#' @return An integer corresponding to the file descriptor of the old
#'   stderr, so that the redirection can be later reverted.
#'
#' @seealso [end_redirect_stderr()].
begin_redirect_stderr <- function(filepath, append = FALSE) {
    .Call(`_r2dup2_begin_redirect_stderr`, filepath, append)
}

#' Reverts the redirection of stderr.
#'
#' This function redirects the standard error (stderr) to its old file
#' descriptor (usually, this ultimately means the R Console).
#'
#' @param old_stderr The file descriptor to the old (previous) stderr,
#'   before the redirection. This corresponds to the return value of
#'   [begin_redirect_stderr()].
#'
#' @return The result code, usually equal to `2`. A negative value,
#'   such as `-1`, indicates an error.
#'
#' @seealso [begin_redirect_stderr()].
end_redirect_stderr <- function(old_stderr) {
    .Call(`_r2dup2_end_redirect_stderr`, old_stderr)
}

